export const buttons = [
    {
        name: "clear",
        value: "c",
        icon: "C",
        color: "primary",
    },
    {
        name: "parentheses",
        value: "()",
        icon: "( )",
        color: "primary",
    },
    {
        name: "percentage",
        value: "%",
        icon: "%",
        color: "primary",
    },
    {
        name: "operator",
        value: "/",
        icon: "÷",
        color: "accent",
    },
    {
        name: "number",
        value: "7",
        icon: "7",
        color: "",
    },
    {
        name: "number",
        value: "8",
        icon: "8",
        color: "",
    },
    {
        name: "number",
        value: "9",
        icon: "9",
        color: "",
    },
    {
        name: "operator",
        value: "*",
        icon: "x",
        color: "accent",
    },
    {
        name: "number",
        value: "4",
        icon: "4",
        color: "",
    },
    {
        name: "number",
        value: "5",
        icon: "5",
        color: "",
    },
    {
        name: "number",
        value: "6",
        icon: "6",
        color: "",
    },
    {
        name: "operator",
        value: "-",
        icon: "-",
        color: "accent",
    },
    {
        name: "number",
        value: "1",
        icon: "1",
        color: "",
    },
    {
        name: "number",
        value: "2",
        icon: "2",
        color: "",
    },
    {
        name: "number",
        value: "3",
        icon: "3",
        color: "",
    },
    {
        name: "operator",
        value: "+",
        icon: "+",
        color: "accent",
    },
    {
        name: "plusminus",
        value: "",
        icon: "+/-",
        color: "",
    },
    {
        name: "number",
        value: "0",
        icon: "0",
        color: "",
    },
    {
        name: "decimal",
        value: ".",
        icon: ".",
        color: "",
    },
    {
        name: "equals",
        value: "=",
        icon: "=",
        color: "accent",
    },
];
